name: Continuous Integration (CI) pipeline
on:
  push:
    branches: [ "main", "development", "release", "hot-fix" ]
  pull_request:
    branches: [ "main" ]

env:
  Solution_Name: GoldenTable.Backend/GoldenTable.sln

jobs:
  build-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarQube Cloud scanner
        shell: powershell
        run: |
          if (!(Test-Path "${{ runner.temp }}\scanner")) {
            New-Item -Path "${{ runner.temp }}\scanner" -ItemType Directory
          }
          dotnet tool update dotnet-sonarscanner --tool-path "${{ runner.temp }}\scanner"

      - name: Restore
        run: dotnet restore "${{ env.Solution_Name }}"

      - name: Begin SonarQube Analysis
        if: matrix.configuration == 'Release'
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"Robert-Andries_The-Golden-Table" /o:"robisca-1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build
        run: dotnet build "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-restore

      - name: Test
        run: dotnet test "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-build --collect:"XPlat Code Coverage"

      - name: End SonarQube Analysis
        if: matrix.configuration == 'Release'
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  snyk-scan:
    runs-on: ubuntu-latest
    environment: SNYK_TOKENS 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore "${{ env.Solution_Name }}" /p:EnableWindowsTargeting=true

      - name: Snyk Security Scan
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file="${{ env.Solution_Name }}" --severity-threshold=medium
